### ISSUE TITLE
Ontwerpsqaudpage

### ISSUE THREAD

**Issue by Safae-e** [reyrey-https/your-tribe-squad-page#3]
![Image (1)](https://github.com/user-attachments/assets/371d977e-2dfa-4f4d-866d-a0a97df11040)

Dit is de design voor onze website met HTML.

**Comment by ArmanVD** [comment]
Maak een container om de kaartjes, stel voor die hoogte dan

header--> 10/15 vh

1e container 85/90 vh

andere containers:
height: 100vh;

dan nemen de containers de hele page over per keer.

geef class names aan de containers, bijv eerste cointainer (die 85/90 vh krijgt) : cont1
geef dan de andere containers een class name can: cont2

zo kan je ze afzonderlijk stylen en kost het je minder code uiteindelijk.

Succes en bij vragen let me know!!
